import os
import json
from openrouter import OpenRouter
from tools import product, cart, address, order
from config import MODELS

MAX_AGENT_STEPS = 20

SYSTEM_MESSAGE = {
    "role": "system",
    "content": """
        You are an e-commerce grocery assistant.
        Your name is Shelf-mates AI.
        DO NOT use emojis in responses.
        Keep the responses simple and casual/professional.
        """
}

tools_interface = [
    # PRODUCT OPS
    product.get_by_category_interface,
    product.get_product_detail_interface,

    # CART OPS
    cart.add_to_cart_interface,
    cart.get_cart_interface,
    cart.decrement_quantity_interface,

    # ADDRESS OPS
    address.add_address_interface,
    address.get_addresses_interface,
    address.update_address_interface,
    address.delete_address_interface,

    # ORDER OPS
    order.place_order_interface
]

TOOL_MAPPING = {
    # PRODUCTS
    "get_products_by_category": product.get_by_category,
    "get_product_detail": product.get_product_detail,
    
    # CART
    "add_to_cart": cart.add_to_cart,
    "get_cart": cart.get_cart,
    "decrement_quantity": cart.decrement_quantity,

    # ADDRESS
    "add_address": address.add_address,
    "get_addresses": address.get_addresses,
    "update_address": address.update_address,
    "delete_address": address.delete_address,

    # ORDER OPS
    "place_order": order.place_order
}

def run_agent(message: str, history: list = None) -> dict:
    """
    Executes the e-commerce grocery agent with the user's message and history.
    Returns a dict containing the final response and the updated conversation history.
    """
    if history is None:
        messages = [SYSTEM_MESSAGE]
    else:
        # Copy history list to avoid mutating the input parameter
        messages = list(history)
        # Verify if system message exists, otherwise prepend it
        has_system = any(msg.get("role") == "system" for msg in messages)
        if not has_system:
            messages.insert(0, SYSTEM_MESSAGE)

    # Append user message
    messages.append({
        "role": "user",
        "content": message
    })

    final_response = "No response generated by the agent."

    try:
        with OpenRouter(api_key=os.getenv("OPENROUTER_API_KEY")) as client:
            for _ in range(MAX_AGENT_STEPS):
                response = client.chat.send(
                    models=MODELS,
                    messages=messages,
                    tools=tools_interface,
                    retries=2
                )

                print("Model used for completion:", response.model)
                message_obj = response.choices[0].message
                messages.append(message_obj)

                # Final answer reached
                if not message_obj.tool_calls:
                    final_response = message_obj.content
                    print(f"\nCHATBOT: {final_response}\n")
                    break

                # Execute all tool calls
                for tool_call in message_obj.tool_calls:
                    tool_name = tool_call.function.name
                    print(f"\n[TOOL] {tool_name}")

                    tool_args = json.loads(tool_call.function.arguments)
                    print("ARGS:", tool_args)

                    if tool_name in TOOL_MAPPING:
                        tool_response = TOOL_MAPPING[tool_name](**tool_args)
                    else:
                        tool_response = f"Error: Tool '{tool_name}' is not supported."
                    print("RESULT:", tool_response)

                    messages.append({
                        "role": "tool",
                        "tool_call_id": tool_call.id,
                        "content": json.dumps(tool_response)
                    })
            else:
                final_response = f"Agent stopped after {MAX_AGENT_STEPS} steps (possible infinite loop)."
                print(f"\n{final_response}\n")

    except Exception as e:
        print(f"\nERROR: {e}\n")
        final_response = f"An error occurred: {str(e)}"
        raise e
    finally:
        formatted_messages = []
        for msg in messages:
            if hasattr(msg, "model_dump"):
                formatted_messages.append(msg.model_dump())
            elif hasattr(msg, "dict"):
                formatted_messages.append(msg.dict())
            else:
                formatted_messages.append(msg)

        try:
            with open("debug_messages.json", "w") as f:
                json.dump(
                    formatted_messages,
                    f,
                    indent=4,
                    default=str
                )
            print("\n**MESSAGE HISTORY DUMPED**\n\n")
        except Exception as log_err:
            print(f"Failed to write debug log: {log_err}")

    return {
        "response": final_response,
        "history": formatted_messages
    }
